### PR TITLE
Support generic variants and reorganize defaults

### PR DESCRIPTION
**Pull request by LuKePicci**
Please check if all edits make sense

### CODE REVIEW

**Comment by bovirus** [comment]
I didn't understand of the meaning of different standard about names for DGA 4130 /DGA 4132.
For me could be better to use the same name scheme. Like

DGA 4130 (TIM) 1.0.3 etc
DGA 4132 (TIM) 1.0.3 etc

I didn't udnerstand why add the product code (AGTEF or AGTHP).
The name (4130/4132) for me is enough

**Comment by LuKePicci** [comment]
AGTEF_1.0.3 is firmware version, not product code

**Comment by bovirus** [comment]
@LujkePicci

The firmware version is 1.0.3.
If you refer to TIM you refer to AGTEF.
It's a double info.

**Comment by LuKePicci** [comment]
Nope, the version string for TIM is AGTEF_1.0.3.
It is the same for Telstra 18.1.c.0215-950-RA
The naming adhere to the same exact standard:
<isp> <firmware_version>

You can check version strings in the TIM gateways if you like,, it is under Device.DeviceInfo.SoftwareVersion

**Comment by bovirus** [comment]
As I mentioned AGTEF if product name for TIM for 4130 as AGTHP is 4132.

If you already mentioned TIM in the name AGTEFF abd AGTHP is nor necessary.

Is not available a TIM firmware for 4130 that is not AGTEF.
And the same for DGA4132 and AGTHP.

If you want use TIM AGTEF/AGTHP don't use 4130/4132 in rhe name

**Comment by LuKePicci** [comment]
Let's try again. **AGTEF_1.0.3** is the version string reported in the firmware. I don't know why dumb people working for TIM used their product name in firmware version, but that's what they did. The caption does not show AGTEF to indicate the product, it shows AGTEF_1.0.3 because that's the version string.
Think to fastweb firmwares, they includes "FW_" as suffix which stands for "fastweb" for each firmware version. We would still use FW_249 as firmware version string, even if we already used "Fastweb" in "Fastweb FW_249" and FW_ is always fastweb and so redundant.

**Comment by LuKePicci** [comment]
> Is not available a TIM firmware for 4130 that is not AGTEF.
> And the same for DGA4132 and AGTHP.

Actually there are some AGTEF series firmwares for 4132...

**Comment by bovirus** [comment]
Then leave original DGA 4130 and DGA 4132 for Technicolor model.
For most of common users using AGTEF or AGTHP don't add important info and only create misunderstanding about reak firmware version.
For most of them firmware version is 1.0m3.
Not AGTEF_1.0.3.

**Comment by LuKePicci** [comment]
Nope, we adhere to a standard naming which matches vendor decisions. Use complete SoftwareVersion as defined and we all would be happy.

Also, we are just talking of a couple of presets that are superseded by the generic ones, it's more likely you will see them disappear.

**Comment by LuKePicci** [comment]
You may notice there are some TG799 preset names I didn't fixed, that's because I have no evidence of what exact device/firmware they relates to. I didn't investigate further because it is better to directly remove them once we know they're no more needed.

**Pull request merged**
